name: Terraform Apply

on:
  push:
    branches:
      - main

env:
  TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
  TF_CLI_CONFIG_FILE: ${{ github.workspace }}/.terraformrc

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure Terraform CLI credentials
        run: |
          cat > .terraformrc <<EOF
          credentials "terraform.your-domain.com" {
            token = "${TFE_TOKEN}"
          }
          EOF

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
