name: Terraform Plan

on:
  pull_request:
    branches:
      - main

env:
  TFE_TOKEN: ${{ secrets.TFE_TOKEN }}
  TF_CLI_CONFIG_FILE: ${{ github.workspace }}/.terraformrc

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Configure Terraform CLI credentials
        run: |
          cat > .terraformrc <<EOF
          credentials "tfe-docker-fdo2.harshit-dixit.sbx.hashidemos.io" {
            token = "${TFE_TOKEN}"
          }
          EOF

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan
